"""
demo_data_generator.py
──────────────────────
Generates realistic sample business data (PDFs, CSVs, JSON) for AI-BOS demo.
Auto-runs on first launch if no data is indexed.

Usage:
    python demo_data_generator.py          # Generate all demo files
    python demo_data_generator.py --clean  # Remove generated files
"""

import csv
import json
import os
import random
import sys
from datetime import datetime, timedelta
from pathlib import Path

DEMO_DIR = Path("demo_data")
DEMO_DIR.mkdir(exist_ok=True)

COMPANIES = ["Gamma AI Labs", "BioSync Corp", "UrbanFlow Tech", "CloudVault Inc",
             "NeuralEdge Systems", "Apex Dynamics", "FuturePath Analytics", "DataSphere Ltd"]
STAGES    = ["Prospecting", "Qualification", "Proposal", "Contract Review", "Closed Won", "Closed Lost"]
REPS      = ["Sarah Chen", "Marcus Johnson", "Priya Patel", "Alex Rivera", "Jordan Smith"]
CHANNELS  = ["Gmail", "Slack", "LinkedIn", "Referral", "Cold Outreach"]

# ── CRM Generator ─────────────────────────────────────────────────────────────

def generate_crm_data(n: int = 25) -> Path:
    """Generate realistic CRM deals JSON."""
    deals = []
    today = datetime.now()
    for i in range(n):
        company  = random.choice(COMPANIES)
        stage    = random.choice(STAGES)
        value    = random.randint(15, 900) * 1000
        days_ago = random.randint(1, 180)
        won      = stage == "Closed Won"
        deals.append({
            "id":            f"DEAL-{1000 + i}",
            "company":       company,
            "contact":       f"{random.choice(['John','Jane','Mike','Lisa'])} {random.choice(['Smith','Lee','Brown','Jones'])}",
            "email":         f"contact@{company.lower().replace(' ', '')}.com",
            "phone":         f"+1-555-{random.randint(1000,9999)}",
            "value":         value,
            "stage":         stage,
            "probability":   95 if won else random.randint(10, 85),
            "owner":         random.choice(REPS),
            "channel":       random.choice(CHANNELS),
            "created_date":  (today - timedelta(days=days_ago)).strftime("%Y-%m-%d"),
            "close_date":    (today + timedelta(days=random.randint(-30, 90))).strftime("%Y-%m-%d"),
            "notes":         f"{'[PII_REDACTED] ' if random.random() > 0.7 else ''}"
                             f"{company} is interested in our enterprise plan. "
                             f"{'Negotiating pricing on Q{} deal.'.format(random.randint(1,4))}"
        })
    path = DEMO_DIR / "crm_data.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(deals, f, indent=2)
    print(f"✅ CRM data → {path} ({n} deals)")
    return path


# ── Activity Log Generator ────────────────────────────────────────────────────

def generate_activity_csv(n: int = 50) -> Path:
    """Generate activity/event log CSV."""
    events = ["Query executed", "Report generated", "File indexed",
              "Connector synced", "Alert triggered", "User login", "Export downloaded"]
    rows   = []
    for i in range(n):
        ts = datetime.now() - timedelta(minutes=random.randint(1, 10080))
        rows.append({
            "timestamp": ts.strftime("%Y-%m-%d %H:%M:%S"),
            "event":     random.choice(events),
            "user":      random.choice(REPS),
            "source":    random.choice(["Gmail", "Slack", "CRM", "File Upload", "Agent"]),
            "status":    random.choice(["success", "success", "success", "warning", "error"]),
            "latency_ms": random.randint(80, 2400),
            "tokens":    random.randint(100, 4000) if (rows and "Query" in rows[-1]["event"]) else 0,
        })
    path = DEMO_DIR / "activity_log.csv"
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=rows[0].keys())
        writer.writeheader()
        writer.writerows(rows)
    print(f"✅ Activity log → {path} ({n} rows)")
    return path


# ── Business Reports Text Generator ──────────────────────────────────────────

def generate_report_txt() -> Path:
    """Generate a sample quarterly report text file."""
    content = f"""QUARTERLY BUSINESS INTELLIGENCE REPORT
Q{random.randint(1,4)} {datetime.now().year}
Generated by AI-BOS IntelForge Engine
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXECUTIVE SUMMARY
─────────────────
Total Pipeline Value:     ${random.randint(3,12)}M
Closed Won This Quarter:  ${random.randint(800,2500)}K
Win Rate:                 {random.randint(28,62)}%
Average Deal Size:        ${random.randint(45,250)}K
Sales Cycle (avg):        {random.randint(21,90)} days

TOP PERFORMING DEALS
────────────────────
1. Gamma AI Labs     — $750K  — Contract Review  — Sarah Chen
2. BioSync Corp      — $420K  — Proposal         — Marcus Johnson
3. UrbanFlow Tech    — $320K  — Closed Won        — Priya Patel
4. CloudVault Inc    — $280K  — Qualification    — Alex Rivera
5. NeuralEdge Sys    — $195K  — Prospecting      — Jordan Smith

PIPELINE ANALYSIS (SWOT)
─────────────────────────
STRENGTHS:
  • Strong enterprise pipeline: 3 deals >$500K in final stages
  • Average response time improved by 34% via AI automation
  • RAG system retrieved relevant context in 97% of queries

WEAKNESSES:
  • SMB segment underperforming vs target (-18%)
  • Contract review bottleneck adding 8 days avg to cycle

OPPORTUNITIES:
  • AI/ML sector showing 42% YoY spend growth
  • 3 warm inbound referrals from existing enterprise clients

THREATS:
  • Competitive pressure from 2 new entrants in space
  • Budget freezes reported in fintech vertical

RECOMMENDATIONS
───────────────
1. Accelerate Gamma AI Labs contract with legal review sprint
2. Launch SMB outbound campaign targeting Series B companies
3. Implement automated follow-up sequences for stale deals
4. Schedule QBRs with top 5 accounts before quarter end

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI-BOS v2.0 | IntelForge Engine | Confidential
"""
    path = DEMO_DIR / "Q_report.txt"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✅ Business report → {path}")
    return path


# ── Knowledge Base Text Generator ────────────────────────────────────────────

def generate_company_handbook() -> Path:
    """Generate Company_Handbook.md-style knowledge document."""
    content = """# IntelForge Company Handbook

## Mission Statement
We build AI-powered business intelligence tools that transform raw organizational
data into actionable insights — empowering teams to make faster, smarter decisions.

## Core Values
- **Data-Driven**: Every decision backed by evidence
- **Privacy-First**: PII anonymization is non-negotiable
- **Speed**: Insights in seconds, not days
- **Reliability**: 99.9% uptime SLA for all pipelines

## Products
### AI-BOS (Business Operating System)
Enterprise RAG platform integrating Gmail, Slack, CRM, and documents into a
unified, queryable knowledge base powered by Gemini 2.0 Flash.

Key features:
- Real-time data ingestion from 4+ sources
- Vector similarity search via Pinecone (cosine, 768d)
- Natural language query interface
- Executive report generation
- Admin dashboard with full audit logs

### Pricing Tiers
| Tier | Price | Vectors | Users |
|------|-------|---------|-------|
| Starter | $99/mo | 50K | 5 |
| Pro | $399/mo | 500K | 25 |
| Enterprise | Custom | Unlimited | Unlimited |

## SLA & Support
- Response time: < 2 hours for critical issues
- Data retention: 90 days activity logs
- Backup: Daily automated snapshots
- Support: 24/7 via Slack + email

## Security & Compliance
- All data encrypted at rest (AES-256) and in transit (TLS 1.3)
- PII anonymized before vectorization
- SOC 2 Type II certification in progress
- GDPR-compliant data handling

## Team
- Engineering: 8 engineers across RAG, infra, and frontend
- Sales: 5 enterprise AEs + 2 SDRs
- Customer Success: 3 dedicated CSMs
"""
    path = DEMO_DIR / "company_handbook.md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"✅ Company handbook → {path}")
    return path


# ── Sample Emails Text ────────────────────────────────────────────────────────

def generate_email_samples() -> Path:
    """Generate sample email conversation text for RAG indexing."""
    emails = [
        {
            "subject": "Re: Gamma AI Labs Enterprise Proposal",
            "from": "sarah.chen@intelforge.com",
            "to": "contact@gammaailabs.com",
            "date": "2026-02-20",
            "body": """Hi David,

Thanks for your time on our call today. As discussed, I'm attaching the
revised proposal for Gamma AI Labs at $750K/year (Enterprise tier).

Key inclusions:
- Unlimited vector storage (currently at 50K vectors)
- Custom RAG pipeline for your Salesforce integration
- Dedicated CSM + SLA: 99.9% uptime
- On-premise deployment option

Please review by Friday so we can get this to legal review next week.

Best,
Sarah Chen | Enterprise AE | IntelForge
"""
        },
        {
            "subject": "Q4 Pipeline Review — Action Required",
            "from": "marcus.johnson@intelforge.com",
            "to": "team@intelforge.com",
            "date": "2026-02-18",
            "body": """Team,

Quick update on Q4 pipeline before Friday's review:

🟢 On Track: BioSync ($420K) — proposal signed, awaiting PO
🟡 At Risk: UrbanFlow ($320K) — champion left company, re-engaging
🔴 Stalled: CloudVault ($280K) — no response in 3 weeks, escalating

Action items:
1. Marcus: Requalify UrbanFlow with new champion by Wed
2. Alex: Send executive outreach to CloudVault CEO
3. Priya: Draft reference case for BioSync legal team

Pipeline total: $3.2M (target: $2.8M) — we're at 114%!

Marcus
"""
        },
    ]
    lines = []
    for e in emails:
        lines.append(f"FROM: {e['from']}")
        lines.append(f"TO: {e['to']}")
        lines.append(f"DATE: {e['date']}")
        lines.append(f"SUBJECT: {e['subject']}")
        lines.append("")
        lines.append(e["body"])
        lines.append("=" * 60)
    path = DEMO_DIR / "sample_emails.txt"
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"✅ Sample emails → {path}")
    return path


# ── Main Generate Function ────────────────────────────────────────────────────

def generate_all() -> list:
    """Generate all demo data files and return list of paths."""
    print("\n🚀 AI-BOS Demo Data Generator")
    print("=" * 40)
    paths = [
        str(generate_crm_data(25)),
        str(generate_activity_csv(50)),
        str(generate_report_txt()),
        str(generate_company_handbook()),
        str(generate_email_samples()),
    ]
    print(f"\n✅ Generated {len(paths)} demo files in ./{DEMO_DIR}/")
    print("💡 Import these in Data Ingestion page to start querying!\n")
    return paths


def clean_all():
    """Remove all generated demo files."""
    import shutil
    if DEMO_DIR.exists():
        shutil.rmtree(DEMO_DIR)
        print(f"🗑️ Removed {DEMO_DIR}/")


def is_demo_needed() -> bool:
    """Returns True if demo data has not been generated yet."""
    return not DEMO_DIR.exists() or not any(DEMO_DIR.iterdir())


if __name__ == "__main__":
    if "--clean" in sys.argv:
        clean_all()
    else:
        generate_all()
